//https://api.themoviedb.org/3/person/6193?api_key=231a9923e67455d132639e888240a6ae&language=en-US

export const actorData = {
  adult: false,
  also_known_as: [
    "Леонардо ДиКаприо",
    "ليوناردو دي كابريو",
    "레오나르도 디카프리오",
    "レオナルド・ディカプリオ",
    "ลีโอนาร์โด ดิแคพรีโอ",
    "莱昂纳多·迪卡普里奥",
    "Leo DiCaprio",
    "Leonardo Wilhelm DiCaprio",
    "Λεονάρντο Ντι Κάπριο",
    "Ντι Κάπριο",
    "Леонардо Ді Капріо",
    "Леонардо ДіКапріо",
    "לאונרדו דיקפריו",
    "ലിയനാർഡോ ഡികാപ്രിയോ",
  ],
  biography:
    "Leonardo DiCaprio (born November 11, 1974) is an American actor, film producer, and environmental activist.\n\nHe began his film career by starring as Josh in Critters 3 before starring in the film adaptation of the memoir This Boy's Life (1993) alongside Robert De Niro. DiCaprio was praised for his supporting role in the drama What's Eating Gilbert Grape (1993), and gained public recognition with leading roles in the drama The Basketball Diaries (1995) and the romantic drama Romeo + Juliet (1996), before achieving international fame with James Cameron's epic romance Titanic (1997) He has been nominated for six Academy Awards—five for acting and one for producing—and in 2016, he won the Academy Award for Best Actor for The Revenant.\n\nDiCaprio is the founder of his own production company, named Appian Way Productions. He is also a committed environmentalist.",
  birthday: "1974-11-11",
  deathday: null,
  gender: 2,
  homepage: "http://leonardodicaprio.com",
  id: 6193,
  imdb_id: "nm0000138",
  known_for_department: "Acting",
  name: "Leonardo DiCaprio",
  place_of_birth: "Los Angeles, California, USA",
  popularity: 18.508,
  profile_path: "/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg",
};

//https://api.themoviedb.org/3/person/6193/images?api_key=231a9923e67455d132639e888240a6ae

export const actorPhotos = {
  id: 6193,
  profiles: [
    {
      aspect_ratio: 0.667,
      height: 1563,
      iso_639_1: null,
      file_path: "/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg",
      vote_average: 5.62,
      vote_count: 22,
      width: 1042,
    },
    {
      aspect_ratio: 0.666,
      height: 1640,
      iso_639_1: null,
      file_path: "/jqbqNrOIB3alGMX6Gh2MbOKMXZO.jpg",
      vote_average: 5.346,
      vote_count: 17,
      width: 1093,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/grEohuTduwtVEgoYMFlQ8Jfei7o.jpg",
      vote_average: 5.282,
      vote_count: 14,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2190,
      iso_639_1: null,
      file_path: "/aLUFp0zWpLVyIOgY0scIpuuKZLE.jpg",
      vote_average: 5.276,
      vote_count: 12,
      width: 1460,
    },
    {
      aspect_ratio: 0.666,
      height: 1481,
      iso_639_1: null,
      file_path: "/jMOipiHOPkVdx9phhKamwlVKEZT.jpg",
      vote_average: 5.276,
      vote_count: 12,
      width: 987,
    },
    {
      aspect_ratio: 0.667,
      height: 750,
      iso_639_1: null,
      file_path: "/nb7e6caBO5BxZ8lyIp9Hzv69oNB.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 500,
    },
  ],
};

//https://api.themoviedb.org/3/person/6193/movie_credits?api_key=231a9923e67455d132639e888240a6ae&language=en-US
export const known_by = {
  cast: [
    {
      original_language: "en",
      original_title: "Romeo + Juliet",
      poster_path: "/zWLZEUE0jrTiLhWQVh8NOJRwIU9.jpg",
      video: false,
      vote_average: 6.8,
      id: 454,
      release_date: "1996-11-01",
      vote_count: 3902,
      title: "Romeo + Juliet",
      adult: false,
      backdrop_path: "/tCTnDPDCPKzKgvBqwJPd9Tj41JS.jpg",
      overview:
        "In director Baz Luhrmann's contemporary take on William Shakespeare's classic tragedy, the Montagues and Capulets have moved their ongoing feud to the sweltering suburb of Verona Beach, where Romeo and Juliet fall in love and secretly wed. Though the film is visually modern, the bard's dialogue remains.",
      genre_ids: [18, 10749],
      popularity: 14.318,
      character: "Romeo",
      credit_id: "52fe4245c3a36847f80114bf",
      order: 0,
    },
    {
      overview:
        "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
      id: 597,
      title: "Titanic",
      adult: false,
      backdrop_path: "/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg",
      genre_ids: [18, 10749],
      original_language: "en",
      original_title: "Titanic",
      poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      vote_count: 19364,
      video: false,
      vote_average: 7.9,
      release_date: "1997-11-18",
      popularity: 78.438,
      character: "Jack Dawson",
      credit_id: "52fe425ac3a36847f80179cf",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/obKCYv66xyqEi0aswy0A9IWHa5f.jpg",
      genre_ids: [18, 53, 28],
      id: 1372,
      original_language: "en",
      original_title: "Blood Diamond",
      overview:
        "An ex-mercenary turned smuggler. A Mende fisherman. Amid the explosive civil war overtaking 1999 Sierra Leone, these men join for two desperate missions: recovering a rare pink diamond of immense value and rescuing the fisherman's son, conscripted as a child soldier into the brutal rebel forces ripping a swath of torture and bloodshed countrywide.",
      poster_path: "/m6rZ3dmqjcTvVNKtqwQ6hxYQ9nk.jpg",
      release_date: "2006-01-26",
      title: "Blood Diamond",
      video: false,
      vote_average: 7.5,
      vote_count: 5689,
      popularity: 30.812,
      character: "Danny Archer",
      credit_id: "52fe42f0c3a36847f802e687",
      order: 0,
    },
    {
      video: false,
      vote_average: 6.4,
      overview:
        "Twenty-something Richard travels to Thailand and finds himself in possession of a strange map. Rumours state that it leads to a solitary beach paradise, a tropical bliss - excited and intrigued, he sets out to find it.",
      release_date: "2000-02-03",
      adult: false,
      backdrop_path: "/bXYJwYuxAufubEE09tt2uCpVrMF.jpg",
      vote_count: 3298,
      genre_ids: [18, 12, 10749, 53],
      id: 1907,
      original_language: "en",
      original_title: "The Beach",
      poster_path: "/Ai1iDX065HBFhtcbxJVwhzJniv0.jpg",
      title: "The Beach",
      popularity: 12.413,
      character: "Richard",
      credit_id: "52fe4320c3a36847f803c4fb",
      order: 0,
    },
    {
      id: 2567,
      original_language: "en",
      original_title: "The Aviator",
      poster_path: "/5vQcBcTIJmzB0IiuWssPGzr8DrU.jpg",
      video: false,
      vote_average: 7.2,
      overview:
        "A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.",
      release_date: "2004-12-17",
      vote_count: 3970,
      adult: false,
      backdrop_path: "/wNBLjvDpvTS3wyOZCecf3Jas7la.jpg",
      title: "The Aviator",
      genre_ids: [18],
      popularity: 13.6,
      character: "Howard Hughes",
      credit_id: "52fe435dc3a36847f804ed4b",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/nb8pMW3o85jATvhz7y6clAFlL1u.jpg",
      genre_ids: [18, 80],
      id: 10474,
      original_language: "en",
      original_title: "The Basketball Diaries",
      overview:
        "A high school basketball player’s life turns upside down after free-falling into the harrowing world of drug addiction.",
      poster_path: "/AhvO1GGDPIgN0hOqZEgaFCbswMK.jpg",
      release_date: "1995-04-21",
      title: "The Basketball Diaries",
      video: false,
      vote_average: 7.3,
      vote_count: 1335,
      popularity: 16.417,
      character: "Jim Carroll",
      credit_id: "52fe43779251416c750116ab",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/a2Aj5ksEo2HOUH3FbGyZCtaJM4C.jpg",
      genre_ids: [18, 36, 80],
      id: 3131,
      original_language: "en",
      original_title: "Gangs of New York",
      overview:
        "It's 1863. America was born in the streets. Amsterdam Vallon returns to the Five Points of America to seek vengeance against the psychotic gangland kingpin, Bill the Butcher, who murdered his father years earlier. With an eager pickpocket by his side and a whole new army, Vallon fights his way to seek vengeance on the Butcher and restore peace in the area.",
      poster_path: "/lemqKtcCuAano5aqrzxYiKC8kkn.jpg",
      release_date: "2002-12-14",
      title: "Gangs of New York",
      video: false,
      vote_average: 7.3,
      vote_count: 4962,
      popularity: 19.451,
      character: "Amsterdam Vallon",
      credit_id: "52fe4389c3a36847f805bbc1",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/zmXMm9DI5qdPPPM92uShv8c2IBP.jpg",
      genre_ids: [18, 10749],
      id: 4148,
      original_language: "en",
      original_title: "Revolutionary Road",
      overview:
        "A young couple living in a Connecticut suburb during the mid-1950s struggle to come to terms with their personal problems while trying to raise their two children. Based on a novel by Richard Yates.",
      poster_path: "/1jYKJEGcgbkEjlKuY94Dv7BVe1P.jpg",
      release_date: "2008-12-19",
      title: "Revolutionary Road",
      video: false,
      vote_average: 6.9,
      vote_count: 2892,
      popularity: 20.389,
      character: "Frank Wheeler",
      credit_id: "52fe43afc3a36847f8067929",
      order: 0,
    },
    {
      backdrop_path: "/8xt8AMb1OKC63AdhNSaYBWxB4Iq.jpg",
      genre_ids: [18, 53, 9648],
      original_language: "en",
      original_title: "Shutter Island",
      poster_path: "/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
      video: false,
      vote_average: 8.2,
      vote_count: 18041,
      overview:
        "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by his troubling visions and also by a mysterious doctor.",
      release_date: "2010-02-14",
      id: 11324,
      title: "Shutter Island",
      adult: false,
      popularity: 45.743,
      character: "Teddy Daniels",
      credit_id: "52fe44269251416c7502a8ab",
      order: 0,
    },
    {
      vote_average: 6.6,
      overview:
        "The CIA’s hunt is on for the mastermind of a wave of terrorist attacks. Roger Ferris is the agency’s man on the ground, moving from place to place, scrambling to stay ahead of ever-shifting events. An eye in the sky – a satellite link – watches Ferris.  At the other end of that real-time link is the CIA’s Ed Hoffman, strategizing events from thousands of miles away. And as Ferris nears the target, he discovers trust can be just as dangerous as it is necessary for survival.",
      release_date: "2008-10-10",
      adult: false,
      backdrop_path: "/iViUI5bTnYkgQ9ty1CXQ8J4obby.jpg",
      vote_count: 2198,
      genre_ids: [28, 18, 53],
      video: false,
      original_language: "en",
      original_title: "Body of Lies",
      poster_path: "/sLjVDPPfNQfAma9XyOqHPClQb2V.jpg",
      title: "Body of Lies",
      id: 12113,
      popularity: 12.942,
      character: "Roger Ferris",
      credit_id: "52fe44b79251416c7503e94f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/xzCe37rMKvYUnrAhIxpLJwv7Xmo.jpg",
      genre_ids: [12, 28, 18],
      id: 9313,
      original_language: "en",
      original_title: "The Man in the Iron Mask",
      overview:
        "Years have passed since the Three Musketeers, Aramis, Athos and Porthos, have fought together with their friend, D'Artagnan. But with the tyrannical King Louis using his power to wreak havoc in the kingdom while his twin brother, Philippe, remains imprisoned, the Musketeers reunite to abduct Louis and replace him with Philippe.",
      poster_path: "/zHE9yRURvA7DyhYtQxkGTfE1Ywi.jpg",
      release_date: "1998-03-12",
      title: "The Man in the Iron Mask",
      video: false,
      vote_average: 6.6,
      vote_count: 2925,
      popularity: 13.446,
      character: "King Louis XIV / Philippe",
      credit_id: "52fe44e6c3a36847f80b0935",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/ii8QGacT3MXESqBckQlyrATY0lT.jpg",
      genre_ids: [28, 878, 12],
      id: 27205,
      original_language: "en",
      original_title: "Inception",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      release_date: "2010-07-15",
      title: "Inception",
      video: false,
      vote_average: 8.3,
      vote_count: 29305,
      popularity: 47.559,
      character: "Dom Cobb",
      credit_id: "52fe4534c3a368484e04de03",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/3FYltaTkmrFeVquPOXbAXgYVuqZ.jpg",
      genre_ids: [10749, 18],
      id: 36834,
      original_language: "en",
      original_title: "Total Eclipse",
      overview:
        "Young, wild poet Arthur Rimbaud and his mentor Paul Verlaine engage in a fierce, forbidden romance while feeling the effects of a hellish artistic lifestyle.",
      poster_path: "/e0j1zDF3ITeTbGTXFGamosCxT4z.jpg",
      release_date: "1995-11-03",
      title: "Total Eclipse",
      video: false,
      vote_average: 6.4,
      vote_count: 369,
      popularity: 10.792,
      character: "Arthur Rimbaud",
      credit_id: "52fe460f9251416c91047b09",
      order: 0,
    },
    {
      original_title: "IMAX Hubble",
      poster_path: "/imskpT2yOJgHPLJsk7D4EQJoFIz.jpg",
      video: false,
      vote_average: 7.0,
      overview:
        "Through the power of IMAX® 3D, Hubble 3D will enable movie-goers to journey through distant galaxies to explore the grandeur and mysteries of our celestial surroundings, and accompany space-walking astronauts as they attempt the most difficult and important tasks in NASA’s history. The film will offer an inspiring and unique look into the Hubble Space Telescope’s legacy and highlight its profound impact on the way we view the universe and ourselves. Narrated by Leonardo DiCaprio, Hubble 3D reunites the Space Station 3D filmmaking team, led by Producer/Director Toni Myers. James Neihouse, Director of Photography, also doubles as the Astronaut crew trainer. Judy Carroll is Associate Producer, and Graeme Ferguson, Co-founder of IMAX and pioneer Producer of many IMAX space films, is Executive Producer. Hubble 3D is an IMAX and Warner Bros. Pictures production, in cooperation with National Aeronautics and Space Administration (NASA).",
      release_date: "2010-03-19",
      id: 44992,
      adult: false,
      backdrop_path: "/p3j7JyXQOLb91yjFPwsbG4BlSJL.jpg",
      vote_count: 74,
      genre_ids: [99],
      title: "IMAX Hubble",
      original_language: "en",
      popularity: 4.861,
      character: "Narrator",
      credit_id: "52fe46a9c3a36847f810b255",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/tb440cwQMRoVHnhYJlzlxfv1ikm.jpg",
      genre_ids: [18, 10749],
      vote_count: 9709,
      original_language: "en",
      original_title: "The Great Gatsby",
      poster_path: "/nimh1rrDDLhgpG8XAYoUZXHYwb6.jpg",
      video: false,
      title: "The Great Gatsby",
      vote_average: 7.4,
      id: 64682,
      overview:
        "An adaptation of F. Scott Fitzgerald's Long Island-set novel, where Midwesterner Nick Carraway is lured into the lavish world of his neighbor, Jay Gatsby. Soon enough, however, Carraway will see through the cracks of Gatsby's nouveau riche existence, where obsession, madness, and tragedy await.",
      release_date: "2013-05-10",
      popularity: 23.638,
      character: "Jay Gatsby",
      credit_id: "52fe46e3c3a368484e0a9783",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/nMfH0LMMFk2ovyURkYvyTI99nSo.jpg",
      genre_ids: [37, 18, 12],
      id: 281957,
      original_language: "en",
      original_title: "The Revenant",
      overview:
        "In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.",
      poster_path: "/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
      release_date: "2015-12-25",
      title: "The Revenant",
      video: false,
      vote_average: 7.5,
      vote_count: 14673,
      popularity: 45.82,
      character: "Hugh Glass",
      credit_id: "53c3fe750e0a26157c00cada",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/2qM3DsUILkozVy61eN0w7J64GOm.jpg",
      id: 88794,
      genre_ids: [18, 80, 36],
      original_language: "en",
      original_title: "J. Edgar",
      poster_path: "/hWHFPhGvCvfHbZCxJSR3n6GsXIf.jpg",
      video: false,
      vote_average: 6.2,
      vote_count: 1817,
      overview:
        "As the face of law enforcement in the United States for almost 50 years, J. Edgar Hoover was feared and admired, reviled and revered. But behind closed doors, he held secrets that would have destroyed his image, his career, and his life.",
      release_date: "2011-11-09",
      title: "J. Edgar",
      popularity: 11.792,
      character: "John Edgar Hoover",
      credit_id: "52fe4a039251416c910c04d9",
      order: 0,
    },
    {
      video: false,
      vote_average: 8.0,
      overview:
        "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
      release_date: "2013-12-25",
      title: "The Wolf of Wall Street",
      adult: false,
      backdrop_path: "/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg",
      id: 106646,
      genre_ids: [80, 18, 35],
      vote_count: 17812,
      original_language: "en",
      original_title: "The Wolf of Wall Street",
      poster_path: "/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
      popularity: 118.738,
      character: "Jordan Belfort",
      credit_id: "52fe4a6dc3a36847f81cd4e7",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/mGBmiWmi7JqeTWnrPicRbkXcsuO.jpg",
      genre_ids: [99],
      id: 410718,
      original_language: "en",
      original_title: "Before the Flood",
      overview:
        "A look at how climate change affects our environment and what society can do to prevent the demise of endangered species, ecosystems, and native communities across the planet.",
      poster_path: "/2fFTLaLbm8Ak7JBSYQ8Mb3jcFx9.jpg",
      release_date: "2016-10-21",
      title: "Before the Flood",
      video: false,
      vote_average: 7.8,
      vote_count: 559,
      popularity: 31.49,
      character: "Self",
      credit_id: "57ecc67f925141356c006216",
      order: 0,
    },
    {
      id: 640,
      adult: false,
      backdrop_path: "/rwcEaZghpbt6mV0lRQ9ymz5oM9B.jpg",
      genre_ids: [18, 80],
      original_language: "en",
      original_title: "Catch Me If You Can",
      poster_path: "/bdW1tDAiW1b4f0onkHKD7ROAVtF.jpg",
      vote_count: 11143,
      video: false,
      title: "Catch Me If You Can",
      vote_average: 7.9,
      overview:
        "A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. An FBI agent makes it his mission to put him behind bars. But Frank not only eludes capture, he revels in the pursuit.",
      release_date: "2002-12-25",
      popularity: 38.584,
      character: "Frank Abagnale Jr.",
      credit_id: "52fe4263c3a36847f801a63f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 329216,
      original_language: "en",
      original_title: "The Foot Shooting Party",
      overview:
        "The lead singer of a band gets drafted for war in Vietnam. So as not to break up the band, he decides to shoot his own foot.",
      poster_path: "/z4BbjUFclmQSu7X4sWZ8WKHIxNz.jpg",
      release_date: "1994-01-01",
      title: "The Foot Shooting Party",
      video: false,
      vote_average: 5.0,
      vote_count: 8,
      popularity: 0.626,
      character: "Bud",
      credit_id: "59e392fc9251410b670003c0",
      order: 0,
    },
    {
      original_language: "en",
      original_title: "Once Upon a Time… in Hollywood",
      poster_path: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
      overview:
        "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
      release_date: "2019-07-24",
      vote_average: 7.5,
      vote_count: 8831,
      adult: false,
      backdrop_path: "/yB2hTgz9CTVYjlMWPSl3LPx5nWj.jpg",
      video: false,
      genre_ids: [35, 18, 53],
      id: 466272,
      title: "Once Upon a Time… in Hollywood",
      popularity: 40.034,
      character: "Rick Dalton",
      credit_id: "5a12c204c3a368628306f0db",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 646380,
      original_language: "en",
      original_title: "Don't Look Up",
      overview:
        "Two low-level astronomers, upon discovering that a meteor will strike the Earth in six months, go on a media tour to try to warn the world but find an unreceptive and unbelieving populace.",
      poster_path: "/yLUMzdc2TLf38Oi3wjfQvjNRIlX.jpg",
      release_date: "",
      title: "Don't Look Up",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 4.219,
      character: "Dr. Randall Mindy",
      credit_id: "5f874bf3d4b9d90037273f96",
      order: 0,
    },
    {
      original_language: "en",
      original_title: "What's Eating Gilbert Grape",
      poster_path: "/8FxWgsfDNosewo7H65oE4QkOb7g.jpg",
      video: false,
      id: 1587,
      overview:
        "Gilbert Grape is a small-town young man with a lot of responsibility. Chief among his concerns are his mother, who is so overweight that she can't leave the house, and his mentally impaired younger brother, Arnie, who has a knack for finding trouble. Settled into a job at a grocery store and an ongoing affair with local woman Betty Carver, Gilbert finally has his life shaken up by the free-spirited Becky.",
      release_date: "1993-12-17",
      vote_count: 2832,
      adult: false,
      backdrop_path: "/f3xI3c7ZjNirN9Lt5CtOi7VURuu.jpg",
      vote_average: 7.7,
      genre_ids: [10749, 18],
      title: "What's Eating Gilbert Grape",
      popularity: 14.276,
      character: "Arnie Grape",
      credit_id: "52fe4301c3a36847f803368d",
      order: 1,
    },
    {
      id: 1422,
      adult: false,
      backdrop_path: "/9RuC3UD6mNZ0p1J6RbfJDUkQ03i.jpg",
      genre_ids: [18, 53, 80],
      vote_count: 11287,
      original_language: "en",
      original_title: "The Departed",
      poster_path: "/kWWAt2FMRbqLFFy8o5R4Zr8cMAb.jpg",
      title: "The Departed",
      video: false,
      vote_average: 8.2,
      release_date: "2006-10-05",
      overview:
        "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
      popularity: 26.538,
      character: 'William "Billy" Costigan, Jr.',
      credit_id: "52fe42f5c3a36847f802fecf",
      order: 1,
    },
    {
      id: 365717,
      video: false,
      vote_count: 93,
      vote_average: 6.3,
      title: "The Audition",
      release_date: "2015-10-03",
      original_language: "en",
      original_title: "The Audition",
      genre_ids: [35],
      backdrop_path: "/54tR3SVqtoH80szs9M4YKJuJfGT.jpg",
      adult: false,
      overview:
        "Robert De Niro and Leonardo DiCaprio must compete for the lead role in Martin Scorsese's next film.",
      poster_path: "/t1PDIeDpJGgI9JPqIRMuG7WDdId.jpg",
      popularity: 4.879,
      character: "Himself",
      credit_id: "5630c9ffc3a3681b5e00f456",
      order: 1,
    },
    {
      id: 438425,
      video: false,
      vote_count: 0,
      vote_average: 0.0,
      title: "The Black Hand",
      original_language: "en",
      original_title: "The Black Hand",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Police officer, Joe Petrosino, seeks justice against a ruthless Italian-American gang in New York. A feature adaptation of Stephan Talty's book 'The Black Hand'.",
      poster_path: null,
      popularity: 0.6,
      character: "Joe Petrosino",
      credit_id: "5890f77b92514103ec00a871",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/tK8K6Mtq8aFAtrsq9FPx072oJla.jpg",
      genre_ids: [80, 18, 53],
      id: 466420,
      original_language: "en",
      original_title: "Killers of the Flower Moon",
      overview:
        "Depicts the serial murder of members of the oil-wealthy Osage Nation in 1920s Oklahoma, a string of brutal crimes that came to be known as the Reign of Terror.",
      poster_path: "/h2ns6sbB4qPIDBSChADaPTsAXG2.jpg",
      release_date: "",
      title: "Killers of the Flower Moon",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 2.332,
      character: "Ernest Burkhart",
      credit_id: "5968f416c3a3686f60021bc8",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/mEoU71g0SjTDEiMTyRj1bV2EfIp.jpg",
      genre_ids: [99],
      id: 213362,
      original_language: "en",
      original_title: "Reflections on Titanic",
      overview:
        "An enthralling and fast-paced four-part documentary feature that covers the making of one of the last major Hollywood epics; Titanic. Cast and crew speak on setting the sinking of the ship against a classic romance. The feature also examines casting and the young couple headlining the film, DiCaprio's and Winslet's on-set friendship and their differing acting styles, the expansive sets and filming locations, the authenticity of the recreated ship, James Cameron's work and dedication, and budgeting. And many more aspects of the film are overviewed.",
      poster_path: null,
      release_date: "2012-09-10",
      title: "Reflections on Titanic",
      video: false,
      vote_average: 7.3,
      vote_count: 18,
      popularity: 2.1,
      character: "Self",
      credit_id: "59e392fc9251410b670003a0",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 486010,
      original_language: "en",
      original_title: "Roosevelt",
      overview: "A biographical drama about President Theodore Roosevelt.",
      poster_path: null,
      release_date: "",
      title: "Roosevelt",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 1.426,
      character: "Theodore Roosevelt",
      credit_id: "5a03b301c3a3680fe7002a25",
      order: 1,
    },
    {
      id: 599379,
      video: false,
      vote_count: 35,
      vote_average: 6.7,
      title: "Ice on Fire",
      release_date: "2019-06-23",
      original_language: "en",
      original_title: "Ice on Fire",
      genre_ids: [99],
      backdrop_path: "/uDqyWBY1sMLUT5W3X89UYKv3coR.jpg",
      adult: false,
      overview:
        "An eye-opening documentary that asks the question: Are we going to let climate change destroy civilization, or will we act on technologies that can reverse it? Featuring never-before-seen solutions on the many ways we can reduce carbon in the atmosphere thus paving the way for temperatures to go down, saving civilization.",
      poster_path: "/9xWrasURZTWbSiulhyxCmJlYTkD.jpg",
      popularity: 6.169,
      character: "Self - Narrator",
      credit_id: "5cdd440bc3a368159dc1194e",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10751, 16, 35, 10402, 10770],
      id: 642488,
      original_language: "en",
      original_title: "Mickey's Safety Club: Street Safe, Street Smart",
      overview:
        "Mickey and his friends take a close look at important street safety situations and tips.",
      poster_path: "/4pfoP47sMClmkXwYYaUfb8gl08T.jpg",
      release_date: "1989-09-01",
      title: "Mickey's Safety Club: Street Safe, Street Smart",
      video: false,
      vote_average: 10.0,
      vote_count: 6,
      popularity: 2.272,
      character: "Alex (voice)",
      credit_id: "5db3545c4b0c630017eba57d",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 508954,
      original_language: "en",
      original_title: "Untitled Evel Knievel Project",
      overview: "Biopic of the famed stuntman Evel Knievel.",
      poster_path: null,
      release_date: "",
      title: "Untitled Evel Knievel Project",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.654,
      character: "Evel Knievel (rumored)",
      credit_id: "5e4252353dd126001a56f5c7",
      order: 1,
    },
    {
      id: 669983,
      video: false,
      vote_count: 1,
      vote_average: 7.0,
      title: "Teslafy Me",
      release_date: "2019-11-01",
      original_language: "en",
      original_title: "Teslafy Me",
      genre_ids: [99, 36],
      backdrop_path: "/uP2EnC2XKUCXKlx3lk2yvcESOu0.jpg",
      adult: false,
      overview:
        "A vision for a world free of pollution and climate problems, with energy available in abundance - are we ready to take up legacy of ingenious inventor Nikola Tesla?",
      poster_path: "/c8w8xJG6roxYnLNVLWll5tvPYBg.jpg",
      popularity: 0.899,
      character: "Self",
      credit_id: "5ea9458b514c4a00268c866d",
      order: 1,
    },
    {
      id: 621751,
      video: false,
      vote_count: 8,
      vote_average: 7.4,
      title: "And We Go Green",
      release_date: "2019-05-23",
      original_language: "en",
      original_title: "And We Go Green",
      genre_ids: [99],
      backdrop_path: "/trZgJaml9vXosGtcZ2gw7gnjPbI.jpg",
      adult: false,
      overview:
        "Professional drivers on the international Formula E circuit — like Formula One, but with eco-friendly electric cars — race for victory across 10 cities.",
      poster_path: "/jO6IqXuWb8hY6145rhsNkRUewoz.jpg",
      popularity: 5.279,
      character: "Self",
      credit_id: "5ebaf191cc277c00206eefe7",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 823102,
      original_language: "en",
      original_title: "Another Round",
      overview: "American remake of the Academy Award-winning Danish film.",
      poster_path: null,
      release_date: "",
      title: "Another Round",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.637,
      character: "",
      credit_id: "6087028a9a8a8a0041fb8fd7",
      order: 1,
    },
    {
      id: 64956,
      video: false,
      vote_count: 260,
      vote_average: 7.3,
      title: "Inception: The Cobol Job",
      release_date: "2010-12-07",
      original_language: "en",
      original_title: "Inception: The Cobol Job",
      genre_ids: [16, 28, 53, 878],
      backdrop_path: "/sABMpHRCmt7qg9q6AFbZ1jPU1Jf.jpg",
      adult: false,
      overview:
        "The Cobol Job is a fourteen-minute animated prequel to Christopher Nolan’s award-winning movie: Inception, detailing the heist on Mr. Kaneda's mind by Nash, Cobb, Arthur, and several Cobol Engineering thugs.",
      poster_path: "/sNxqwtyHMNQwKWoFYDqcYTui5Ok.jpg",
      popularity: 8.873,
      character: "Cobb",
      credit_id: "60d40d77e9c0dc00265721b1",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/6N6VUUR1gzbCkiGpQzvRREv3Od1.jpg",
      genre_ids: [18],
      original_language: "en",
      original_title: "This Boy's Life",
      poster_path: "/4qei4K95gQpjK6fOfBJvVSYDIHi.jpg",
      vote_count: 675,
      video: false,
      vote_average: 7.1,
      title: "This Boy's Life",
      overview:
        "When a son and mother move to Seattle in hopes for a better life, the mother meets a seemingly polite man. Things go south when the man turns out to be abusive, endangering their lives. As the mother struggles to maintain hope in an impossible situation, the son has plans to escape.",
      release_date: "1993-04-09",
      id: 8092,
      popularity: 10.854,
      character: "Tobias Wolff",
      credit_id: "52fe4493c3a36847f809dcd5",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/dXGjxSaKV02s1It9i0IF7HhVQ8l.jpg",
      genre_ids: [18],
      original_language: "en",
      original_title: "Marvin's Room",
      poster_path: "/89YFVzS7Unsb9knSKnVZJvGgeAz.jpg",
      vote_count: 443,
      video: false,
      vote_average: 6.7,
      title: "Marvin's Room",
      overview:
        "A leukemia patient attempts to end a 20-year feud with her sister to get her bone marrow.",
      release_date: "1996-12-18",
      id: 9819,
      popularity: 9.11,
      character: "Hank Lacker",
      credit_id: "52fe4534c3a36847f80c1e31",
      order: 2,
    },
    {
      overview:
        "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
      release_date: "2012-12-25",
      id: 68718,
      adult: false,
      backdrop_path: "/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg",
      genre_ids: [18, 37],
      title: "Django Unchained",
      original_language: "en",
      original_title: "Django Unchained",
      poster_path: "/4E4TTsCXVFyhBtYu9fKy0gIT3Ih.jpg",
      video: false,
      vote_average: 8.1,
      vote_count: 20799,
      popularity: 37.163,
      character: "Calvin J. Candie",
      credit_id: "52fe479fc3a368484e0d12db",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 696842,
      original_language: "en",
      original_title: "Scorsese's Goodfellas",
      overview:
        "In this produced by Brett Ratner new retrospective documentary we hear from cast members and additional participants include Harvey Keitel, Leonardo DiCaprio and Terence Winter, creator of Boardwalk Empire and screenwriter of The Wolf of Wall Street. The program gives us thoughts about Scorsese's approach to the material, casting, characters, and performances, costumes and period details, photography, music, and retrospective thoughts about the film. It is filled with memorable stories and observations from a wide array of commentators.",
      poster_path: "/eQPjyYlRduhxDP7To0kMfMaOkiU.jpg",
      release_date: "2015-05-05",
      title: "Scorsese's Goodfellas",
      video: true,
      vote_average: 8.0,
      vote_count: 5,
      popularity: 1.666,
      character: "Himself",
      credit_id: "5ea369c73faba00025455101",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/1Q0FrRbywFPjseam7mwt6MYKXe7.jpg",
      genre_ids: [99],
      id: 402970,
      original_language: "en",
      original_title: "Notes on an American Film Director at Work",
      overview:
        "Filmmaker Jonas Mekas follows his friend, film director Martin Scorsese, and his cast and crew, through various locations during the shooting of his film The Departed, released in 2006.",
      poster_path: "/8Ah2goGOhoR1i7jwOOaie10reoS.jpg",
      release_date: "2008-01-01",
      title: "Notes on an American Film Director at Work",
      video: false,
      vote_average: 5.0,
      vote_count: 1,
      popularity: 1.594,
      character: "Self",
      credit_id: "5ebdb25a6d675a00207a4e8b",
      order: 2,
    },
    {
      video: false,
      title: "The Quick and the Dead",
      overview:
        "A mysterious woman comes to compete in a quick-draw elimination tournament, in a town taken over by a notorious gunman.",
      release_date: "1995-02-09",
      vote_count: 1174,
      adult: false,
      backdrop_path: "/wwdzmWC1Ra9SqPBrtCyRNJ4oYUO.jpg",
      id: 12106,
      genre_ids: [37, 28, 53],
      vote_average: 6.5,
      original_language: "en",
      original_title: "The Quick and the Dead",
      poster_path: "/fQk89YaQdeBcS7AmlKODKOxIAPU.jpg",
      popularity: 14.5,
      character: "Fee Herod 'The Kid'",
      credit_id: "52fe44b69251416c7503e5a7",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/5NaM9m6lA5JcIZolbNWvUCgsIeV.jpg",
      genre_ids: [18, 35],
      id: 9466,
      original_language: "en",
      original_title: "Celebrity",
      overview:
        "The career and personal life of writer Lee are at a standstill, so he divorces his bashful wife, Robin, and dives into a new job as an entertainment journalist. His assignments take him to the swankiest corners of Manhattan, but as he jumps from one lavish party to another and engages in numerous empty romances, he starts to doubt the worth of his work. Meanwhile, top TV producer Tony falls for Robin and introduces her to the world of celebrity.",
      poster_path: "/3pbcMORRjqYgfx87CXexLw32gk.jpg",
      release_date: "1998-09-07",
      title: "Celebrity",
      video: false,
      vote_average: 6.0,
      vote_count: 319,
      popularity: 7.9,
      character: "Brandon",
      credit_id: "52fe44fbc3a36847f80b59b3",
      order: 3,
    },
    {
      genre_ids: [35, 27, 878],
      original_language: "en",
      original_title: "Critters 3",
      poster_path: "/frjklbq23pRgBjhekEq6drQkrZm.jpg",
      video: false,
      vote_average: 5.1,
      id: 12702,
      release_date: "1991-12-11",
      vote_count: 235,
      overview:
        "In what appears to be a cross between Critters and The Towering Inferno, the residents of a shoddy L.A. apartment block are chased up to the roof by hoards of the eponymous hairy horrors.",
      adult: false,
      backdrop_path: "/kb0jFY1rDTxQeJRt1HJs2SQZdiz.jpg",
      title: "Critters 3",
      popularity: 13.378,
      character: "Josh",
      credit_id: "52fe45169251416c7504b579",
      order: 3,
    },
    {
      id: 37857,
      video: false,
      vote_count: 53,
      vote_average: 5.6,
      title: "Don's Plum",
      release_date: "2001-02-10",
      original_language: "en",
      original_title: "Don's Plum",
      genre_ids: [18],
      backdrop_path: "/7xrlSPGDO4CDT6IHTctDlkYxTzw.jpg",
      adult: false,
      overview:
        "A group of Los Angeles teenagers meet every day at their local diner hangout to discus their latest misadventures with their miserable lives",
      poster_path: "/pXWiYyWaNUfZaud5maDWDFJ5AG7.jpg",
      popularity: 4.301,
      character: "Derek",
      credit_id: "59e392fc9251410b6700039a",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/f9oNiTUoharENGjdDufG0aDbSIO.jpg",
      genre_ids: [53, 18],
      id: 9264,
      original_language: "en",
      original_title: "Poison Ivy",
      overview:
        "A seductive teen befriends an introverted high school student and schemes her way into the lives of her wealthy family.",
      poster_path: "/igwGf0qNka1qH1HPijgbABfUfB4.jpg",
      release_date: "1992-05-08",
      title: "Poison Ivy",
      video: false,
      vote_average: 5.3,
      vote_count: 230,
      popularity: 10.353,
      character: "Guy",
      credit_id: "59e392fc9251410b67000398",
      order: 4,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 459682,
      original_language: "en",
      original_title: "Catch Me If You Can: Behind the Camera",
      overview:
        "A behind the scenes look at the making of Stephen Spielberg's Catch Me If You Can.",
      poster_path: "/wQXvOy2hpfLscTorrzhy2icveVZ.jpg",
      release_date: "2003-05-06",
      title: "Catch Me If You Can: Behind the Camera",
      video: false,
      vote_average: 8.9,
      vote_count: 9,
      popularity: 2.744,
      character: "Himself",
      credit_id: "59e392fc9251410b670003be",
      order: 5,
    },
    {
      adult: false,
      backdrop_path: "/hoML3xQNqd6aRcUXiVlPhrSIfAR.jpg",
      genre_ids: [99, 10770],
      id: 467062,
      original_language: "en",
      original_title: "Spielberg",
      overview:
        "A documentary on the life and career of one of the most influential film directors of all time, Steven Spielberg.",
      poster_path: "/2AAvIR2PHoxNITgLDOkXXlWLlua.jpg",
      release_date: "2017-10-05",
      title: "Spielberg",
      video: false,
      vote_average: 7.5,
      vote_count: 186,
      popularity: 8.352,
      character: "Self",
      credit_id: "59dc0ef3c3a368620d05bb6f",
      order: 6,
    },
    {
      original_language: "en",
      original_title: "The 11th Hour",
      poster_path: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      vote_average: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 66,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genre_ids: [99],
      popularity: 6.07,
      character: "Himself",
      credit_id: "59e392fc9251410b670003a2",
      order: 6,
    },
    {
      id: 379053,
      video: false,
      vote_count: 11,
      vote_average: 6.2,
      title: "A World Unseen: The Revenant",
      release_date: "2016-01-21",
      original_language: "en",
      original_title: "A World Unseen: The Revenant",
      genre_ids: [99],
      backdrop_path: "/5EX5VvLGBM02RulMyn7YJWJJsKH.jpg",
      adult: false,
      overview:
        "A new documentary directed by Eliot Rausch exploring the production of Alejandro G. Iñárritu's The Revenant",
      poster_path: "/p0ZLWJzw6FAWtKv30pwsTA4zI08.jpg",
      popularity: 1.511,
      character: "Himself",
      credit_id: "59e392fc9251410b670003a8",
      order: 6,
    },
    {
      adult: false,
      backdrop_path: "/3rw5aaSAzE64mdkeOk6N3KPlSWJ.jpg",
      genre_ids: [99],
      original_language: "en",
      original_title: "Leonardo DiCaprio: Most Wanted!",
      id: 792166,
      vote_count: 6,
      title: "Leonardo DiCaprio: Most Wanted!",
      vote_average: 7.9,
      video: false,
      overview:
        "From his juvenile, tormented, heroic roles, which made him a global phenomenon, to his darker mature roles, a portrait of American actor Leonardo DiCaprio, a consummate performer and probably the most successful film star of his generation.",
      release_date: "2021-01-29",
      poster_path: "/oO8CotrnqhHAGbVMcCqNHrb89pP.jpg",
      popularity: 2.789,
      character: "Self - Actor (archive footage)",
      credit_id: "603627d4223e20003f043074",
      order: 6,
    },
    {
      video: true,
      vote_average: 7.0,
      overview:
        "A documentary about the making of Martin Scorsese's 'The Departed' and its influences.",
      release_date: "2007-04-25",
      adult: false,
      backdrop_path: null,
      vote_count: 1,
      genre_ids: [99],
      title: "Crossing Criminal Cultures",
      original_language: "en",
      original_title: "Crossing Criminal Cultures",
      poster_path: "/oSReXz9rJ2W4esTS8cHP76MBI49.jpg",
      id: 615443,
      popularity: 0.6,
      character: "Himself",
      credit_id: "5d2b1c1fa294f042db2bfd77",
      order: 7,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 803107,
      original_language: "ja",
      original_title: "JAPANARAMA! Psycho TV From Japan Vol. 1",
      overview:
        "No wonder the Japanese are such a stressed-out society: They enjoy mutilating and torturing each other just for the hell of it...not to mention for the benefits of the television cameras, and Japanarama! Volume 1 captures two hours of only the very twisted of psycho TV from Japan. Much of this party tape utilizes footage from bizarre and cruel game shows. Rounding out the tape are some great cheesey commercials, mostly for foods that look grossly unappetizing, and some with sell out American celebrities. A few scenes are shown from various weird Far East movies.",
      poster_path: "/2jdhkjw3qQ5BJq4Vkv5BuQ6fAEV.jpg",
      release_date: "",
      title: "JAPANARAMA! Psycho TV From Japan Vol. 1",
      video: true,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.881,
      character: "",
      credit_id: "6043b06a2b8a43005798afe9",
      order: 10,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 376478,
      original_language: "en",
      original_title: "X-Girl",
      overview:
        "A short film created to promote Kim Gordon and Daisy von Furth's second collection for their clothing line, X-Girl.",
      poster_path: "/ygg8JjT9LIr9J0DOM8GT4xjSNwS.jpg",
      release_date: "1995-01-01",
      title: "X-Girl",
      video: false,
      vote_average: 3.0,
      vote_count: 1,
      popularity: 0.6,
      character: "Himself (uncredited)",
      credit_id: "5dd3e0a7b39e3500138c9267",
      order: 12,
    },
    {
      id: 36863,
      video: false,
      vote_count: 6,
      vote_average: 7.5,
      title: "Everything's Cool",
      release_date: "2007-01-01",
      original_language: "en",
      original_title: "Everything's Cool",
      genre_ids: [99],
      backdrop_path: "/9zje9bA21EQuY9MHcGWCl2coApS.jpg",
      adult: false,
      overview:
        'In this documentary, filmmakers Daniel B. Gold and Judith Helfand (Blue Vinyl) follow a troupe of self-proclaimed global warming "warriors" on a mission to get the world to care about rising temperatures and melting polar ice caps. Taking a topic that\'s inherently serious and applying their signature blend of humor and emotional heft, Gold and Helfand advance the environmental dialogue in a surprisingly entertaining way.',
      poster_path: "/3Au8x9Yq1W9dssEFQBKPDacvSOz.jpg",
      popularity: 0.892,
      character: "Self (archive footage)",
      credit_id: "5f962ac6fcf9070037e99dc3",
      order: 15,
    },
    {
      original_title: "kid 90",
      id: 795859,
      video: false,
      vote_average: 7.4,
      overview:
        "As a teenager in the '90s, Soleil Moon Frye carried a video camera everywhere she went. She documented hundreds of hours of footage and then locked it away for over 20 years.",
      release_date: "2021-03-12",
      vote_count: 18,
      adult: false,
      backdrop_path: "/dtnVDcsXzpkFeij8J6IkNEQI2hY.jpg",
      title: "kid 90",
      genre_ids: [99],
      poster_path: "/5yK7ySo3E3w1JDjqq9WNk9oIwsw.jpg",
      original_language: "en",
      popularity: 3.116,
      character: "Self (archiveFootage)",
      credit_id: "6075edce3f4833002972d82a",
      order: 15,
    },
    {
      poster_path: "/rGPwMYUeygsUAmo0NS8IPlhQEfH.jpg",
      id: 631143,
      overview:
        "A detailed account of the life and artistic career of legendary filmmaker Quentin Tarantino, from his early days as a video club manager to the scandalous fall in disgrace of producer Harvey Weinstein. A story about how to shoot eight great movies and become an icon of modern pop culture.",
      vote_average: 7.3,
      vote_count: 71,
      release_date: "2019-10-21",
      adult: false,
      backdrop_path: "/ulKw0ytuwp9L2RmikvO3mg8Ll6b.jpg",
      video: false,
      genre_ids: [99],
      title: "QT8: The First Eight",
      original_language: "en",
      original_title: "QT8: The First Eight",
      popularity: 6.211,
      character: "Self (archive footage)",
      credit_id: "60d4f33563a69500465099b6",
      order: 20,
    },
    {
      id: 75009,
      video: false,
      vote_count: 3,
      vote_average: 5.0,
      title: "The Concert for New York City",
      release_date: "2001-10-20",
      original_language: "en",
      original_title: "The Concert for New York City",
      genre_ids: [99, 36, 10402],
      backdrop_path: null,
      adult: false,
      overview:
        "The Concert for New York City took place on October 20, 2001 at Madison Square Garden. It was a celebration of the strength of New York and a thank-you to the heroic firefighters, police officers and rescue workers who saved tens of thousands of lives on September 11th. More than 6000 firefighters, police officers and rescue workers attended as guests.",
      poster_path: "/rq0LTMvPdBTxkjW2ka3HOOT5bet.jpg",
      popularity: 2.67,
      character: "Self",
      credit_id: "5b8f195b925141739b00252f",
      order: 29,
    },
  ],
  crew: [
    {
      title: "The Assassination of Richard Nixon",
      vote_average: 6.6,
      overview:
        "It’s 1974 and Sam Bicke has lost everything. His wife leaves him with his three kids, his boss fires him, his brother turns away from him, and the bank won’t give him any money to start anew. He tries to find someone to blame for his misfortunes and comes up with the President of the United States who he plans to murder.",
      release_date: "2004-05-17",
      adult: false,
      backdrop_path: "/gXvmhujLzYRXMQPZNBDFUD3RnEg.jpg",
      vote_count: 210,
      genre_ids: [18, 36, 53],
      id: 842,
      original_language: "en",
      original_title: "The Assassination of Richard Nixon",
      poster_path: "/5jOOvAVvP0XtwC5yYQpQCy4cjq1.jpg",
      video: false,
      popularity: 10.687,
      credit_id: "52fe4280c3a36847f8023e8b",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: "/nxPpDLO1sYlOqpNdL4Pc7athIlu.jpg",
      genre_ids: [18],
      id: 10316,
      original_language: "en",
      original_title: "The Ides of March",
      overview:
        "Dirty tricks stand to soil an ambitious young press spokesman's idealism in a cutthroat presidential campaign where 'victory' is relative.",
      poster_path: "/w8t4UnJnC24S9ygoaFgmMzRbErd.jpg",
      release_date: "2011-09-24",
      title: "The Ides of March",
      video: false,
      vote_average: 6.7,
      vote_count: 1872,
      popularity: 11.246,
      credit_id: "52fe43589251416c7500cc6d",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_language: "en",
      original_title: "The 11th Hour",
      poster_path: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      vote_average: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 66,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genre_ids: [99],
      popularity: 6.07,
      credit_id: "52fe43ddc3a36847f8074d69",
      department: "Production",
      job: "Producer",
    },
    {
      backdrop_path: "/yrR1Hk2NbWupDHfroGt2spdE1Jm.jpg",
      genre_ids: [27, 53, 9648],
      original_language: "en",
      original_title: "Orphan",
      poster_path: "/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg",
      video: false,
      vote_average: 6.9,
      vote_count: 3654,
      overview:
        "After losing their baby, a married couple adopt 9-year old Esther, who may not be as innocent as she seems.",
      release_date: "2009-07-24",
      title: "Orphan",
      id: 21208,
      adult: false,
      popularity: 93.984,
      credit_id: "52fe440fc3a368484e00d3b9",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 25354,
      original_language: "en",
      original_title: "Gardener of Eden",
      overview:
        "When a young deli-counter clerk and general slacker in New Jersey accidentally saves a young woman from a serial rapist, he becomes convinced that his new role in life is to become a vigilante.",
      poster_path: "/6Vq91cEOicwNKMqlLtYmg1WPdW.jpg",
      release_date: "2007-04-26",
      title: "Gardener of Eden",
      video: false,
      vote_average: 6.0,
      vote_count: 20,
      popularity: 2.63,
      credit_id: "52fe44c3c3a368484e0356f7",
      department: "Production",
      job: "Producer",
    },
    {
      video: false,
      vote_average: 8.0,
      overview:
        "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
      release_date: "2013-12-25",
      title: "The Wolf of Wall Street",
      adult: false,
      backdrop_path: "/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg",
      id: 106646,
      genre_ids: [80, 18, 35],
      vote_count: 17812,
      original_language: "en",
      original_title: "The Wolf of Wall Street",
      poster_path: "/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
      popularity: 118.738,
      credit_id: "52fe4a6dc3a36847f81cd4d1",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/hxBTaMW9qkZ4LG5ZnPxMoHZOk9K.jpg",
      genre_ids: [53, 18, 80],
      id: 164457,
      original_language: "en",
      original_title: "Out of the Furnace",
      overview:
        "Two brothers live in the economically-depressed Rust Belt, when a cruel twist of fate lands one in prison. His brother is then lured into one of the most violent crime rings in the Northeast.",
      poster_path: "/cOuQQ4eRpSBxb0G9OXzWE1pHPeq.jpg",
      release_date: "2013-12-06",
      title: "Out of the Furnace",
      video: false,
      vote_average: 6.6,
      vote_count: 1471,
      popularity: 9.782,
      credit_id: "52fe4c7ac3a36847f82304ab",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/zSJT1sKGRKcmP4I9b8dIOuepw6I.jpg",
      genre_ids: [12, 28, 53],
      id: 375588,
      title: "Robin Hood",
      vote_count: 2280,
      vote_average: 5.9,
      video: false,
      release_date: "2018-11-21",
      overview:
        "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
      original_title: "Robin Hood",
      poster_path: "/AiRfixFcfTkNbn2A73qVJPlpkUo.jpg",
      original_language: "en",
      popularity: 54.124,
      credit_id: "59a65be2c3a368280f008355",
      department: "Production",
      job: "Producer",
    },
    {
      backdrop_path: "/zfaajfDILOqfC6cbfjDy4a7obp6.jpg",
      genre_ids: [14, 53, 27],
      original_language: "en",
      original_title: "Red Riding Hood",
      poster_path: "/ixQYkLeLlTTnAoT32dukndyObB6.jpg",
      video: false,
      vote_average: 6.0,
      id: 49730,
      overview:
        "Valerie is in love with a brooding outsider, Peter, but her parents have arranged for her to marry another man – who is wealthy. Unwilling to lose each other, Valerie and Peter plan to run away together when they learn that Valerie's older sister has been killed by a werewolf that prowls the dark forest surrounding their village. Hungry for revenge, the people call on famed werewolf hunter, Father Solomon, to help them kill the wolf. But Solomon's arrival brings unintended consequences as he warns that the wolf, who takes human form by day, could be any one of them.",
      release_date: "2011-03-11",
      vote_count: 2598,
      title: "Red Riding Hood",
      adult: false,
      popularity: 23.685,
      credit_id: "53675f5ac3a3681220004476",
      department: "Production",
      job: "Producer",
    },
    {
      id: 2567,
      original_language: "en",
      original_title: "The Aviator",
      poster_path: "/5vQcBcTIJmzB0IiuWssPGzr8DrU.jpg",
      video: false,
      vote_average: 7.2,
      overview:
        "A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.",
      release_date: "2004-12-17",
      vote_count: 3970,
      adult: false,
      backdrop_path: "/wNBLjvDpvTS3wyOZCecf3Jas7la.jpg",
      title: "The Aviator",
      genre_ids: [18],
      popularity: 13.6,
      credit_id: "5573120b925141318e002459",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 346683,
      original_language: "en",
      original_title: "Wilson",
      overview:
        "A look at the role U.S. President Woodrow Wilson played in World War I.",
      poster_path: null,
      release_date: "",
      title: "Wilson",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "5590cca0925141758300007b",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/mGBmiWmi7JqeTWnrPicRbkXcsuO.jpg",
      genre_ids: [99],
      id: 410718,
      original_language: "en",
      original_title: "Before the Flood",
      overview:
        "A look at how climate change affects our environment and what society can do to prevent the demise of endangered species, ecosystems, and native communities across the planet.",
      poster_path: "/2fFTLaLbm8Ak7JBSYQ8Mb3jcFx9.jpg",
      release_date: "2016-10-21",
      title: "Before the Flood",
      video: false,
      vote_average: 7.8,
      vote_count: 559,
      popularity: 31.49,
      credit_id: "57ecc6cb9251410c5b00d2c5",
      department: "Production",
      job: "Executive Producer",
    },
    {
      release_date: "2016-09-02",
      adult: false,
      backdrop_path: "/fHkDtfR9u4tDfL803OOtTwfDqhF.jpg",
      genre_ids: [99],
      vote_count: 48,
      original_language: "en",
      original_title: "The Ivory Game",
      poster_path: "/dWFyOj0wk8AFLqC8PH5LRD3kJht.jpg",
      title: "The Ivory Game",
      video: false,
      vote_average: 7.6,
      id: 411023,
      overview:
        "Wildlife activists and investigators put their lives on the line to battle the illegal African ivory trade, in this suspenseful on-the-ground documentary.",
      popularity: 4.902,
      credit_id: "581f9178c3a3685553004726",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: "/rfHyl8C2ghhahZUtxYLvK9ru4zK.jpg",
      genre_ids: [80, 18, 53],
      id: 259695,
      original_language: "en",
      original_title: "Live by Night",
      overview:
        "A story set in the Prohibition Era and centered on a group of individuals and their dealings in the world of organized crime.",
      poster_path: "/7kxSjMrjJIXqgFMAT4CvKF5nnF6.jpg",
      release_date: "2016-12-25",
      title: "Live by Night",
      video: false,
      vote_average: 6.2,
      vote_count: 1021,
      popularity: 17.533,
      credit_id: "5846be30c3a368490300b526",
      department: "Production",
      job: "Producer",
    },
    {
      id: 438425,
      video: false,
      vote_count: 0,
      vote_average: 0.0,
      title: "The Black Hand",
      original_language: "en",
      original_title: "The Black Hand",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Police officer, Joe Petrosino, seeks justice against a ruthless Italian-American gang in New York. A feature adaptation of Stephan Talty's book 'The Black Hand'.",
      poster_path: null,
      popularity: 0.6,
      credit_id: "5890f7d4c3a368702400a96f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/zAfG4ZmpNfKSyr8MVn1CHjgYYXx.jpg",
      genre_ids: [18, 36, 80],
      original_language: "en",
      original_title: "Richard Jewell",
      poster_path: "/5Lgkm8jt4roAFPZQ52fKMhVmDaZ.jpg",
      video: false,
      vote_average: 7.5,
      id: 292011,
      overview:
        "Richard Jewell thinks quick, works fast, and saves hundreds, perhaps thousands, of lives after a domestic terrorist plants several pipe bombs and they explode during a concert, only to be falsely suspected of the crime by sloppy FBI work and sensational media coverage.",
      release_date: "2019-12-13",
      vote_count: 1579,
      title: "Richard Jewell",
      popularity: 11.539,
      credit_id: "593e09e59251416945011b3b",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/bRQUXL1GRRLrkH183eS81CUk4Kj.jpg",
      genre_ids: [80, 53, 18],
      id: 146238,
      original_language: "en",
      original_title: "Runner Runner",
      overview:
        "When a poor college student who cracks an online poker game goes bust, he arranges a face-to-face with the man he thinks cheated him, a sly offshore entrepreneur.",
      poster_path: "/7xZY1BZWIgkKI2zSfE9qHiADaOF.jpg",
      release_date: "2013-09-24",
      title: "Runner Runner",
      video: false,
      vote_average: 5.7,
      vote_count: 958,
      popularity: 8.816,
      credit_id: "5972914bc3a36815930249b1",
      department: "Production",
      job: "Producer",
    },
    {
      original_title: "Cowspiracy: The Sustainability Secret",
      poster_path: "/5rn3jsTgqQWPQRDof3eHT3wd500.jpg",
      id: 282297,
      vote_average: 7.8,
      overview:
        "Follow the shocking, yet humorous, journey of an aspiring environmentalist, as he daringly seeks to find the real solution to the most pressing environmental issues and true path to sustainability.",
      release_date: "2014-07-01",
      vote_count: 370,
      adult: false,
      backdrop_path: "/7KYqBgUtQGInqHVEMRnlyneuCpA.jpg",
      video: false,
      genre_ids: [99],
      title: "Cowspiracy: The Sustainability Secret",
      original_language: "en",
      popularity: 11.182,
      credit_id: "5b10bdc60e0a26307c00e2dc",
      department: "Production",
      job: "Executive Producer",
    },
    {
      video: false,
      vote_average: 7.8,
      overview:
        "A documentary focused on plastic pollution in the world's oceans.",
      release_date: "2016-09-22",
      adult: false,
      backdrop_path: "/bQGDBSxjovzlOpOnqK6g3HVcAID.jpg",
      vote_count: 64,
      genre_ids: [99],
      id: 431339,
      original_language: "en",
      original_title: "A Plastic Ocean",
      poster_path: "/8Ry1c7rVYonb4y8ELpdxvvMQWB1.jpg",
      title: "A Plastic Ocean",
      popularity: 9.383,
      credit_id: "5b31ddf90e0a263ffc00a3d5",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 486010,
      original_language: "en",
      original_title: "Roosevelt",
      overview: "A biographical drama about President Theodore Roosevelt.",
      poster_path: null,
      release_date: "",
      title: "Roosevelt",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 1.426,
      credit_id: "5b31de7c0e0a26400a00a6bd",
      department: "Production",
      job: "Producer",
    },
    {
      vote_average: 8.0,
      overview:
        "Virunga in the Democratic Republic of the Congo is Africa’s oldest national park, a UNESCO world heritage site, and a contested ground among insurgencies seeking to topple the government that see untold profits in the land. Among this ongoing power struggle, Virunga also happens to be the last natural habitat for the critically endangered mountain gorilla. The only thing standing in the way of the forces closing in around the gorillas: a handful of passionate park rangers and journalists fighting to secure the park’s borders and expose the corruption of its enemies. Filled with shocking footage, and anchored by the surprisingly deep and gentle characters of the gorillas themselves, Virunga is a galvanizing call to action around an ongoing political and environmental crisis in the Congo.",
      release_date: "2014-11-07",
      adult: false,
      backdrop_path: "/pmhPTJnEJhvvZhK92cfCpnE3TqZ.jpg",
      vote_count: 163,
      genre_ids: [99, 10752],
      video: false,
      original_language: "en",
      original_title: "Virunga",
      poster_path: "/b59YdJZyRUu04hnWdmmz4kPjbTF.jpg",
      id: 263614,
      title: "Virunga",
      popularity: 6.607,
      credit_id: "5b31ddd1c3a368533500a420",
      department: "Production",
      job: "Executive Producer",
    },
    {
      backdrop_path: "/oO7jZXPbzjvc4F5icsYqFGHzqSr.jpg",
      genre_ids: [53, 27],
      original_language: "en",
      original_title: "Delirium",
      poster_path: "/j2jIkjrASnjtwCmCNDwh9LDWvq9.jpg",
      video: false,
      vote_average: 5.7,
      vote_count: 174,
      overview:
        "A man recently released from a mental institute inherits a mansion after his parents die. After a series of disturbing events, he comes to believe it is haunted.",
      release_date: "2018-05-10",
      title: "Delirium",
      id: 340601,
      adult: false,
      popularity: 9.295,
      credit_id: "5b31de3cc3a368532200b2bd",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 505675,
      original_language: "en",
      original_title: "Harker",
      overview:
        "Evil rules the night. It spreads its black hand across the land. No one is safe from its wrath and sooner or later it will devour everyone. One man has made it his purpose to journey into the heart of hell and face the devil himself to take back what is rightfully his. This is the story of Jonathan Harker. This Orlando based team have challenged themselves to create a silent film in HARKER, a puppet short. They have gone to great lengths to re-create the true feeling of a silent movie. Puppets are created with an exceptional visual style, much like the German Expressionists films The Cabinet of Dr. Caligari and Nosferatu.",
      poster_path: null,
      release_date: "",
      title: "Harker",
      video: false,
      vote_average: 8.5,
      vote_count: 2,
      popularity: 0.6,
      credit_id: "5b31e04c0e0a26400a00a78f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 339161,
      original_language: "en",
      original_title: "Catching the Sun",
      overview:
        "An unemployed American worker, a Tea Party activist, and a Chinese solar entrepreneur. But who wins and who loses the battle for power in the 21st century? Through interwoven character dramas spanning the U.S. and China, Catching the Sun explores the global economic race to lead the clean energy future.",
      poster_path: "/bH27INYEvDCD38aJ816aowcCncX.jpg",
      release_date: "2015-06-12",
      title: "Catching the Sun",
      video: false,
      vote_average: 7.0,
      vote_count: 10,
      popularity: 1.847,
      credit_id: "5b31dda20e0a26401400b390",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [12, 18, 9648],
      id: 331042,
      original_language: "en",
      original_title: "The Deep Blue Good-By",
      overview: "Detective Travis McGee sets out to locate a WWII treasure.",
      poster_path: null,
      release_date: "",
      title: "The Deep Blue Good-By",
      video: false,
      vote_average: 8.3,
      vote_count: 4,
      popularity: 0.992,
      credit_id: "5b31dee29251413c9b009b8f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/x16W2mBhIoAmMn8Ds1GHqE2AnWh.jpg",
      genre_ids: [99],
      id: 565255,
      original_language: "en",
      original_title: "Struggle: The Life and Lost Art of Szukalski",
      overview:
        "The remarkable life story of the pre-war Polish artist Stanislav Szukalski, documented by the American friends he made late in life.",
      poster_path: "/uvBJHkVGLwAqUbiNtxsUfVITBcT.jpg",
      release_date: "2018-12-21",
      title: "Struggle: The Life and Lost Art of Szukalski",
      video: false,
      vote_average: 7.8,
      vote_count: 47,
      popularity: 4.819,
      credit_id: "5c47cf919251415e3451e17a",
      department: "Production",
      job: "Producer",
    },
    {
      id: 599379,
      video: false,
      vote_count: 35,
      vote_average: 6.7,
      title: "Ice on Fire",
      release_date: "2019-06-23",
      original_language: "en",
      original_title: "Ice on Fire",
      genre_ids: [99],
      backdrop_path: "/uDqyWBY1sMLUT5W3X89UYKv3coR.jpg",
      adult: false,
      overview:
        "An eye-opening documentary that asks the question: Are we going to let climate change destroy civilization, or will we act on technologies that can reverse it? Featuring never-before-seen solutions on the many ways we can reduce carbon in the atmosphere thus paving the way for temperatures to go down, saving civilization.",
      poster_path: "/9xWrasURZTWbSiulhyxCmJlYTkD.jpg",
      popularity: 6.169,
      credit_id: "5ccacc70925141044e24de56",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [12, 10751],
      id: 548699,
      original_language: "en",
      original_title: "Captain Planet",
      overview:
        "A story centered around an environmentally friendly superhero.",
      poster_path: null,
      release_date: "",
      title: "Captain Planet",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "5d317750caab6d1640a41373",
      department: "Production",
      job: "Producer",
    },
    {
      id: 621751,
      video: false,
      vote_count: 8,
      vote_average: 7.4,
      title: "And We Go Green",
      release_date: "2019-05-23",
      original_language: "en",
      original_title: "And We Go Green",
      genre_ids: [99],
      backdrop_path: "/trZgJaml9vXosGtcZ2gw7gnjPbI.jpg",
      adult: false,
      overview:
        "Professional drivers on the international Formula E circuit — like Formula One, but with eco-friendly electric cars — race for victory across 10 cities.",
      poster_path: "/jO6IqXuWb8hY6145rhsNkRUewoz.jpg",
      popularity: 5.279,
      credit_id: "5d4c4f90c68b6900140fc8f2",
      department: "Production",
      job: "Producer",
    },
    {
      overview:
        "The vaquita, the world’s smallest whale, is nearing extinction as its habitat is destroyed  by Mexican cartels and the Chinese Mafia, who harvest the totoaba fish, the “cocaine of the sea.” Environmental activists, the Mexican navy, and undercover investigators are fighting back against this illegal multimillion-dollar business.",
      release_date: "2019-09-20",
      adult: false,
      backdrop_path: "/3fwEwcrPjDCPzRpOXtc1KAQ6PDA.jpg",
      genre_ids: [99],
      vote_count: 42,
      original_language: "en",
      original_title: "Sea of Shadows",
      poster_path: "/8qUT6hgWwAZCrB4Df5d4pygYmmR.jpg",
      title: "Sea of Shadows",
      video: false,
      vote_average: 7.7,
      id: 566219,
      popularity: 11.036,
      credit_id: "5da5258c8a88b20011c6f995",
      department: "Production",
      job: "Executive Producer",
    },
    {
      id: 668344,
      video: false,
      vote_count: 0,
      vote_average: 0.0,
      title: "The Corporation",
      release_date: "",
      original_language: "en",
      original_title: "The Corporation",
      genre_ids: [28, 80, 53],
      backdrop_path: null,
      adult: false,
      overview:
        'A story of Jose Miguel Battle (a.k.a. the Godfather), the leader of an organized crime group, called "The Corporation", which was involved in illegal activities ranging from loansharking and gambling to drug trafficking and murder.',
      poster_path: null,
      popularity: 0.6,
      credit_id: "5e33ab5598f1f10014014356",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 718375,
      original_language: "en",
      original_title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      overview:
        "A feature adaptation of the 2014 Oscar-nominated documentary VIRUNGA.",
      poster_path: null,
      release_date: "",
      title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 1.34,
      credit_id: "5ef249c143cd5400337aa537",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/avjz9a8wyh09JyuIcjIWMA75yyD.jpg",
      genre_ids: [99],
      id: 451474,
      original_language: "en",
      original_title: "The Last Shaman",
      overview:
        "James gives himself 12 months before he has 'a license to kill himself', he sets off to the amazon rainforest with hopes of finding a shaman who can save his life.",
      poster_path: "/52wrrla3cOVadcNNBNf3HVKeX7d.jpg",
      release_date: "2017-05-12",
      title: "The Last Shaman",
      video: false,
      vote_average: 7.2,
      vote_count: 18,
      popularity: 4.269,
      credit_id: "601709f1cb8028003f148f63",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_title: "kid 90",
      id: 795859,
      video: false,
      vote_average: 7.4,
      overview:
        "As a teenager in the '90s, Soleil Moon Frye carried a video camera everywhere she went. She documented hundreds of hours of footage and then locked it away for over 20 years.",
      release_date: "2021-03-12",
      vote_count: 18,
      adult: false,
      backdrop_path: "/dtnVDcsXzpkFeij8J6IkNEQI2hY.jpg",
      title: "kid 90",
      genre_ids: [99],
      poster_path: "/5yK7ySo3E3w1JDjqq9WNk9oIwsw.jpg",
      original_language: "en",
      popularity: 3.116,
      credit_id: "60342785c6006d003db9bd4e",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 18],
      id: 823102,
      original_language: "en",
      original_title: "Another Round",
      overview: "American remake of the Academy Award-winning Danish film.",
      poster_path: null,
      release_date: "",
      title: "Another Round",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 0.637,
      credit_id: "608702c255c926007826aa81",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/lQushXG0zdVcvcZDVUktFBEf4qE.jpg",
      genre_ids: [99],
      id: 821546,
      original_language: "en",
      original_title: "The Loneliest Whale: The Search for 52",
      overview:
        "The mysterious 52 Hertz wale emits a call unrecognized by other whales, leading to a life of solitude.",
      poster_path: "/vD6tmAcHSFI16KohyrccNP8IklP.jpg",
      release_date: "2021-07-09",
      title: "The Loneliest Whale: The Search for 52",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 5.492,
      credit_id: "60c13b441ac2920076ac1a84",
      department: "Production",
      job: "Executive Producer",
    },
    {
      overview:
        "Follows a group of scientists, researchers and activist exposing the extinction behind sharks.",
      release_date: "2021-07-13",
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      vote_count: 0,
      original_language: "en",
      id: 844584,
      poster_path: null,
      vote_average: 0.0,
      video: false,
      title: "Fin",
      original_title: "Fin",
      popularity: 2.228,
      credit_id: "60d5023ea6d93100739a2119",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_language: "en",
      original_title: "The 11th Hour",
      poster_path: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      vote_average: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 66,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genre_ids: [99],
      popularity: 6.07,
      credit_id: "52fe43ddc3a36847f8074d5d",
      department: "Writing",
      job: "Screenplay",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 718375,
      original_language: "en",
      original_title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      overview:
        "A feature adaptation of the 2014 Oscar-nominated documentary VIRUNGA.",
      poster_path: null,
      release_date: "",
      title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
      popularity: 1.34,
      credit_id: "60819c49c439c0002a3bf862",
      department: "Writing",
      job: "Writer",
    },
  ],
  id: 6193,
};
