//https://api.themoviedb.org/3/movie/popular?api_key=231a9923e67455d132639e888240a6ae&language=en-US&page=1

export const popular = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/uAQrHntCccFpvxp75XdQgqexlJd.jpg",
      genre_ids: [16, 35, 10751, 14],
      id: 508943,
      original_language: "en",
      original_title: "Luca",
      overview:
        "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
      popularity: 5454.689,
      poster_path: "/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
      release_date: "2021-06-17",
      title: "Luca",
      video: false,
      vote_average: 8.2,
      vote_count: 1735,
    },
    {
      adult: false,
      backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
      genre_ids: [878, 28, 53],
      id: 581726,
      original_language: "en",
      original_title: "Infinite",
      overview:
        "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
      popularity: 3578.349,
      poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
      release_date: "2021-09-08",
      title: "Infinite",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/z2UtGA1WggESspi6KOXeo66lvLx.jpg",
      genre_ids: [878, 53, 27],
      id: 520763,
      original_language: "en",
      original_title: "A Quiet Place Part II",
      overview:
        "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
      popularity: 3212.59,
      poster_path: "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
      release_date: "2021-05-21",
      title: "A Quiet Place Part II",
      video: false,
      vote_average: 7.9,
      vote_count: 1086,
    },
    {
      adult: false,
      backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
      genre_ids: [28, 12, 80],
      id: 385128,
      original_language: "en",
      original_title: "F9",
      overview:
        "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      popularity: 2980.038,
      poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      release_date: "2021-05-19",
      title: "F9",
      video: false,
      vote_average: 7.8,
      vote_count: 328,
    },
    {
      adult: false,
      backdrop_path: "/8ChCpCYxh9YXusmHwcE9YzP0TSG.jpg",
      genre_ids: [35, 80],
      id: 337404,
      original_language: "en",
      original_title: "Cruella",
      overview:
        "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
      popularity: 2432.272,
      poster_path: "/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
      release_date: "2021-05-26",
      title: "Cruella",
      video: false,
      vote_average: 8.5,
      vote_count: 3559,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 80],
      id: 385687,
      original_language: "en",
      original_title: "Fast & Furious 10",
      overview: "The tenth installment in the Fast Saga.",
      popularity: 2077.005,
      poster_path: "/2DyEk84XnbJEdPlGF43crxfdtHH.jpg",
      title: "Fast & Furious 10",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
      genre_ids: [80, 28, 53],
      id: 637649,
      original_language: "en",
      original_title: "Wrath of Man",
      overview:
        "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
      popularity: 2007.549,
      poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
      release_date: "2021-04-22",
      title: "Wrath of Man",
      video: false,
      vote_average: 7.8,
      vote_count: 1178,
    },
    {
      adult: false,
      backdrop_path: "/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg",
      genre_ids: [27, 9648, 53],
      id: 423108,
      original_language: "en",
      original_title: "The Conjuring: The Devil Made Me Do It",
      overview:
        "Paranormal investigators Ed and Lorraine Warren encounter what would become one of the most sensational cases from their files. The fight for the soul of a young boy takes them beyond anything they'd ever seen before, to mark the first time in U.S. history that a murder suspect would claim demonic possession as a defense.",
      popularity: 1791.982,
      poster_path: "/xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg",
      release_date: "2021-05-25",
      title: "The Conjuring: The Devil Made Me Do It",
      video: false,
      vote_average: 8,
      vote_count: 2744,
    },
    {
      adult: false,
      backdrop_path: "/3RMbkXS4ocMmoJyAD3ZsWbm32Kx.jpg",
      genre_ids: [28, 12, 18, 878, 53],
      id: 615658,
      original_language: "en",
      original_title: "Awake",
      overview:
        "After a sudden global event wipes out all electronics and takes away humankind’s ability to sleep, chaos quickly begins to consume the world. Only Jill, an ex-soldier with a troubled past, may hold the key to a cure in the form of her own daughter. The question is, can Jill safely deliver her daughter and save the world before she herself loses her mind.",
      popularity: 1473.502,
      poster_path: "/uZkNbB8isWXHMDNoIbqXvmslBMC.jpg",
      release_date: "2021-06-09",
      title: "Awake",
      video: false,
      vote_average: 6.2,
      vote_count: 418,
    },
    {
      adult: false,
      backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
      genre_ids: [28, 14, 12],
      id: 460465,
      original_language: "en",
      original_title: "Mortal Kombat",
      overview:
        "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
      popularity: 1362.781,
      poster_path: "/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg",
      release_date: "2021-04-07",
      title: "Mortal Kombat",
      video: false,
      vote_average: 7.5,
      vote_count: 3157,
    },
    {
      adult: false,
      backdrop_path: "/9WlJFhOSCPnaaSmsrv0B4zA8iUb.jpg",
      genre_ids: [28, 80, 878, 27, 53],
      id: 503736,
      original_language: "en",
      original_title: "Army of the Dead",
      overview:
        "Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble: venturing into the quarantine zone to pull off the greatest heist ever attempted.",
      popularity: 1330.031,
      poster_path: "/z8CExJekGrEThbpMXAmCFvvgoJR.jpg",
      release_date: "2021-05-14",
      title: "Army of the Dead",
      video: false,
      vote_average: 6.5,
      vote_count: 1759,
    },
    {
      adult: false,
      backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
      genre_ids: [14, 12, 28],
      id: 399566,
      original_language: "en",
      original_title: "Godzilla vs. Kong",
      overview:
        "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
      popularity: 1319.006,
      poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
      release_date: "2021-03-24",
      title: "Godzilla vs. Kong",
      video: false,
      vote_average: 8,
      vote_count: 6201,
    },
    {
      adult: false,
      backdrop_path: "/vqEjXzWdzPbV2DZ7bk29weDFiDl.jpg",
      genre_ids: [16, 12, 10751, 37],
      id: 637693,
      original_language: "en",
      original_title: "Spirit Untamed",
      overview:
        "Lucky Prescott's life is changed forever when she moves from her home in the city to a small frontier town and befriends a wild mustang named Spirit.",
      popularity: 1267.036,
      poster_path: "/5cbGVDmRMYVzkq5cItZ7cYlDdDR.jpg",
      release_date: "2021-05-20",
      title: "Spirit Untamed",
      video: false,
      vote_average: 7.8,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: "/uEWCi9fc89m9qS5SNshlvxkSsLJ.jpg",
      genre_ids: [27, 53],
      id: 159211,
      original_language: "en",
      original_title: "The Haunting of Helena",
      overview:
        "After a divorce, Sophia moves to the south of Italy with her daughter, Helena. Their new home, an apartment within an austere building of the fascist age, is a chance for them to start a new life. But inside an old storage room hides a mysterious closet and a buried secret. After the loss of Helena’s first baby tooth, a chilling obsession begins and an apparition haunts her sleep...",
      popularity: 1044.444,
      poster_path: "/iB8rf8FYHGlrbmLybCo6Mpg8hNt.jpg",
      release_date: "2013-01-14",
      title: "The Haunting of Helena",
      video: false,
      vote_average: 5.2,
      vote_count: 100,
    },
    {
      adult: false,
      backdrop_path: "/4kIRrW1AlHP5Idne8CPHeQt8nR5.jpg",
      genre_ids: [16, 10751, 35, 14],
      id: 550205,
      original_language: "en",
      original_title: "Wish Dragon",
      overview:
        "Determined teen Din is longing to reconnect with his childhood best friend when he meets a wish-granting dragon who shows him the magic of possibilities.",
      popularity: 1069.45,
      poster_path: "/lnPf6hzANL6pVQTxUlsNYSuhT5l.jpg",
      release_date: "2021-01-15",
      title: "Wish Dragon",
      video: false,
      vote_average: 8.3,
      vote_count: 297,
    },
    {
      adult: false,
      backdrop_path: "/A0xW7GgeFQoQmPOn7HcHkBQ5nlb.jpg",
      genre_ids: [53, 28],
      id: 817451,
      original_language: "en",
      original_title: "Endangered Species",
      overview:
        "Jack Halsey takes his wife, their adult kids, and a friend for a dream vacation in Kenya. But as they venture off alone into a wilderness park, their safari van is flipped over by an angry rhino, leaving them injured and desperate. Then, as two of them go in search of rescue, a bloody, vicious encounter with a leopard and a clan of hyenas incites a desperate fight for survival.",
      popularity: 1004.341,
      poster_path: "/ccsSqbpEqr2KK9eMvoeF8ERFCd5.jpg",
      release_date: "2021-05-27",
      title: "Endangered Species",
      video: false,
      vote_average: 6.7,
      vote_count: 53,
    },
    {
      adult: false,
      backdrop_path: "/miOnymJ0dN2psWBB8Vleo3fUyrc.jpg",
      genre_ids: [18, 10751, 35],
      id: 607259,
      original_language: "en",
      original_title: "Fatherhood",
      overview:
        "A widowed new dad copes with doubts, fears, heartache and dirty diapers as he sets out to raise his daughter on his own. Inspired by a true story.",
      popularity: 920.921,
      poster_path: "/pR2fzm82fl0giommpo310LBOMbV.jpg",
      release_date: "2021-06-18",
      title: "Fatherhood",
      video: false,
      vote_average: 8,
      vote_count: 424,
    },
    {
      adult: false,
      backdrop_path: "/jw6ASGRT2gi8EjCImpGtbiJ9NQ9.jpg",
      genre_ids: [27],
      id: 632357,
      original_language: "en",
      original_title: "The Unholy",
      overview:
        "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
      popularity: 922.994,
      poster_path: "/bShgiEQoPnWdw4LBrYT5u18JF34.jpg",
      release_date: "2021-03-31",
      title: "The Unholy",
      video: false,
      vote_average: 7,
      vote_count: 1093,
    },
    {
      adult: false,
      backdrop_path: "/roALP6N8Q2h57mBxecQJazs0IFz.jpg",
      genre_ids: [27],
      id: 676845,
      original_language: "es",
      original_title: "Juega Conmigo",
      overview:
        "Sofia, an insecure young woman, begins babysitting two troublesome siblings that turn her job into a complete living hell. That is until a devilish presence starts messing with the trio and they must band together to fight the demon away.",
      popularity: 881.11,
      poster_path: "/iM5kNvZzcMSmWv7CFTxnTu5zfoa.jpg",
      release_date: "2021-02-25",
      title: "Come Play With Me",
      video: false,
      vote_average: 7,
      vote_count: 89,
    },
    {
      adult: false,
      backdrop_path: "/fPGeS6jgdLovQAKunNHX8l0avCy.jpg",
      genre_ids: [28, 53, 10752],
      id: 567189,
      original_language: "en",
      original_title: "Tom Clancy's Without Remorse",
      overview:
        "An elite Navy SEAL uncovers an international conspiracy while seeking justice for the murder of his pregnant wife.",
      popularity: 951.631,
      poster_path: "/rEm96ib0sPiZBADNKBHKBv5bve9.jpg",
      release_date: "2021-04-29",
      title: "Tom Clancy's Without Remorse",
      video: false,
      vote_average: 7.2,
      vote_count: 1264,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const topRated = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/gNBCvtYyGPbjPCT1k3MvJuNuXR6.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 15.475,
      poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.7,
      vote_count: 2964,
    },
    {
      adult: false,
      backdrop_path: "/irlfhYtHfhZuYpsq2LAoh308NFe.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 39.552,
      poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.7,
      vote_count: 19155,
    },
    {
      adult: false,
      backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
      genre_ids: [10749],
      id: 724089,
      original_language: "en",
      original_title: "Gabriel's Inferno Part II",
      overview:
        "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
      popularity: 7.558,
      poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
      release_date: "2020-07-31",
      title: "Gabriel's Inferno Part II",
      video: false,
      vote_average: 8.7,
      vote_count: 1277,
    },
    {
      adult: false,
      backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 37.729,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.7,
      vote_count: 14457,
    },
    {
      adult: false,
      backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
      genre_ids: [10749, 35],
      id: 761053,
      original_language: "en",
      original_title: "Gabriel's Inferno Part III",
      overview:
        "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.  Watch now : https://stream4k.xyz",
      popularity: 15.303,
      poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
      release_date: "2020-11-19",
      title: "Gabriel's Inferno Part III",
      video: false,
      vote_average: 8.7,
      vote_count: 837,
    },
    {
      adult: false,
      backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
      genre_ids: [10749],
      id: 696374,
      original_language: "en",
      original_title: "Gabriel's Inferno",
      overview:
        "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
      popularity: 7.615,
      poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
      release_date: "2020-05-29",
      title: "Gabriel's Inferno",
      video: false,
      vote_average: 8.7,
      vote_count: 2069,
    },
    {
      adult: false,
      backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 29.575,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-11-30",
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 11505,
    },
    {
      adult: false,
      backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather: Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 34.022,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather: Part II",
      video: false,
      vote_average: 8.6,
      vote_count: 8637,
    },
    {
      adult: false,
      backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
      genre_ids: [10749, 16, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 119.083,
      poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.6,
      vote_count: 7588,
    },
    {
      adult: false,
      backdrop_path: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 45.337,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.5,
      vote_count: 11484,
    },
    {
      adult: false,
      backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 114.32,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.5,
      vote_count: 11610,
    },
    {
      adult: false,
      backdrop_path: "/9guoVF7zayiiUq5ulKQpt375VIy.jpg",
      genre_ids: [16, 28, 14, 12],
      id: 592350,
      original_language: "ja",
      original_title: "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
      overview:
        "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
      popularity: 322.142,
      poster_path: "/zGVbrulkupqpbwgiNedkJPyQum4.jpg",
      release_date: "2019-12-20",
      title: "My Hero Academia: Heroes Rising",
      video: false,
      vote_average: 8.5,
      vote_count: 744,
    },
    {
      adult: false,
      backdrop_path: "/8ChCpCYxh9YXusmHwcE9YzP0TSG.jpg",
      genre_ids: [35, 80],
      id: 337404,
      original_language: "en",
      original_title: "Cruella",
      overview:
        "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
      popularity: 2432.272,
      poster_path: "/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
      release_date: "2021-05-26",
      title: "Cruella",
      video: false,
      vote_average: 8.5,
      vote_count: 3559,
    },
    {
      adult: false,
      backdrop_path: "/88J6waYVTta8Qz3iX3qUeWNA5d5.jpg",
      genre_ids: [18, 10749],
      id: 447362,
      original_language: "en",
      original_title: "Life in a Year",
      overview:
        "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
      popularity: 94.579,
      poster_path: "/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
      release_date: "2020-11-27",
      title: "Life in a Year",
      video: false,
      vote_average: 8.5,
      vote_count: 668,
    },
    {
      adult: false,
      backdrop_path: "/5Nz25DPXfQaSpDgce42Y3kFg9G4.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 38.27,
      poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.5,
      vote_count: 12412,
    },
    {
      adult: false,
      backdrop_path: "/hQQTE285UQB1lLY1XiioQ77LYnC.jpg",
      genre_ids: [16, 35, 10749, 18, 14],
      id: 572154,
      original_language: "ja",
      original_title: "青春ブタ野郎はゆめみる少女の夢を見ない",
      overview:
        "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
      popularity: 149.858,
      poster_path: "/7Ai8vNEv4zEveh12JViGikoVPVV.jpg",
      release_date: "2019-06-15",
      title: "Rascal Does Not Dream of a Dreaming Girl",
      video: false,
      vote_average: 8.5,
      vote_count: 279,
    },
    {
      adult: false,
      backdrop_path: "/1fOsyhVz5qyX2rl1qqX6KImVhTx.jpg",
      genre_ids: [18, 35],
      id: 644479,
      original_language: "es",
      original_title: "Dedicada a mi ex",
      overview:
        "The film tells the story of Ariel, a 21-year-old who decides to form a rock band to compete for a prize of ten thousand dollars in a musical band contest, this as a last option when trying to get money to save their relationship and reunite with his ex-girlfriend, which breaks due to the trip she must make to Finland for an internship. Ariel with her friend Ortega, decides to make a casting to find the other members of the band, although they do not know nothing about music, thus forming a band with members that have diverse and opposite personalities.",
      popularity: 23.207,
      poster_path: "/riAooJrFvVhotyaOgoI0WR7okSe.jpg",
      release_date: "2019-11-01",
      title: "Dedicated to my ex",
      video: false,
      vote_average: 8.5,
      vote_count: 395,
    },
    {
      adult: false,
      backdrop_path: "/yHtB4KHNigx3ZoxDvQbW2SOXGfq.jpg",
      genre_ids: [16, 10751, 12, 14],
      id: 441130,
      original_language: "en",
      original_title: "Wolfwalkers",
      overview:
        "In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.",
      popularity: 20.323,
      poster_path: "/uRkDrsKwCCZC9zdHZs2CFTt1ATZ.jpg",
      release_date: "2020-10-26",
      title: "Wolfwalkers",
      video: false,
      vote_average: 8.5,
      vote_count: 484,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 47.7,
      poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.5,
      vote_count: 21308,
    },
    {
      adult: false,
      backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 20.917,
      poster_path: "/7sf9CgJz30aXDvrg7DYYUQ2U91T.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.5,
      vote_count: 5645,
    },
  ],
  total_pages: 442,
  total_results: 8840,
};


//https://api.themoviedb.org/3/genre/movie/list?api_key=231a9923e67455d132639e888240a6ae&language=en-US

export const genres = {
  genres: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
    { id: 10770, name: "TV Movie" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "War" },
    { id: 37, name: "Western" },
  ],
};